Repository luk707/filemanager, pull requests merged in 2025-03, with the labels that each got.

#22 Implement inspector pane and major overhaul of application shell
  client/app/api/files.ts
  client/app/components/app-sidebar.tsx
  client/app/components/file-grid.tsx
  client/app/components/inspector-sidebar.tsx
  client/app/components/ui/button.tsx
  client/app/components/ui/sidebar.tsx
  client/app/components/ui/tabs.tsx
  client/app/hooks/use-inspector.ts
  client/app/layouts/shell.tsx
  client/app/pages/file-browser.tsx
  client/app/root.tsx
  client/package-lock.json
  client/package.json
Labels: enhancement, frontend

#63 45 add unit tests for stat endpoint
  server/poetry.lock
  server/pyproject.toml
  server/tests/test_main.py
Labels: backend, testing

#65 Add contributors to the README
  README.md
Labels: documentation

#69 feat: mino file repo stat and s3 unit tests
  server/poetry.lock
  server/pyproject.toml
  server/src/main.py
  server/src/repositories/files/minio.py
  server/tests/conftest.py
  server/tests/repositories/files/test_minio.py
Labels: backend, testing

#66 Configure storybook
  README.md
  client/.gitignore
  client/.storybook/main.ts
  client/.storybook/preview.ts
  client/app/components/ui/button.stories.tsx
  client/package-lock.json
  client/package.json
  client/sb-vite.config.ts
Labels: documentation, frontend
